### ISSUE TITLE
Dependency cycles between patron and book

### ISSUE THREAD

**Issue by bslota** [ddd-by-examples/library#23]
There are dependency cycles between `patron` and `book` packages.

![image](https://user-images.githubusercontent.com/22646896/55835239-effb9e00-5b1b-11e9-870d-6af17b2efab7.png)

Problematic dependencies include: events, PatronId, book types

**Comment by dosdebug** [comment]
@bslota Because `book` has holds by some `patron` and `patron` can hold any `book`. So, this dependency cycle is implicit by requirement, no?

Explain me please if I misunderstood.

**Comment by dosdebug** [comment]
Also, this ticket is working of https://github.com/ddd-by-examples/library/issues/19

**Comment by bslota** [comment]
Duplicate of #19

@dosdebug you're right. I'm closing the issue. We will move the discussion there.
