### ISSUE TITLE
Example mapping - not clear

### ISSUE THREAD

**Issue by ccristian** [ddd-by-examples/library#29]
https://github.com/ddd-by-examples/library/blob/master/docs/example-mapping.md

There is the Checkout book on hold 👍 
and one of the stickers below is "The one when patron wants to collect book which in NOT on hold"

Why in the category of books on hold there is an example of book not on hold ?

Thanks

**Comment by bslota** [comment]
Hi @ccristian ! Thank you for your question! Regarding the example you mentioned, you are absolutely right that the title sticky note is confusing. I just renamed it to **Checking out** and also fixed the stickies belonging to it (**Collecting** should be replaced with **Checking out**).
