### ISSUE TITLE
Test MeteredDomainEventPublisherSpec is not running during build.

### ISSUE THREAD

**Issue by KamilWitkowski7** [ddd-by-examples/library#46]
I cloned repository from master branch today.

When running `mvn clean install` I don't see every test:

> [INFO] --- maven-failsafe-plugin:2.22.1:integration-test (default) @ library ---
> [INFO] 
> [INFO] -------------------------------------------------------
> [INFO]  T E S T S
> [INFO] -------------------------------------------------------
> [INFO] Running io.pillopl.library.catalogue.CatalogueDatabaseIT
> (...)
> [INFO] Running io.pillopl.library.lending.book.infrastructure.BookDatabaseRepositoryIT
> (...)
> [INFO] Running io.pillopl.library.lending.book.infrastructure.DuplicateHoldFoundIT
> (...)
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.468 s - in io.pillopl.library.lending.book.infrastructure.DuplicateHoldFoundIT
> [INFO] Running io.pillopl.library.lending.book.infrastructure.FindAvailableBookInDatabaseIT
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in io.pillopl.library.lending.book.infrastructure.FindAvailableBookInDatabaseIT
> [INFO] Running io.pillopl.library.lending.book.infrastructure.FindBookOnHoldInDatabaseIT
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.pillopl.library.lending.book.infrastructure.FindBookOnHoldInDatabaseIT
> [INFO] Running io.pillopl.library.lending.book.infrastructure.OptimisticLockingBookAggregateIT
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 s - in io.pillopl.library.lending.book.infrastructure.OptimisticLockingBookAggregateIT
> [INFO] Running io.pillopl.library.lending.dailysheet.infrastructure.FindingHoldsInDailySheetDatabaseIT
> [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.15 s - in io.pillopl.library.lending.dailysheet.infrastructure.FindingHoldsInDailySheetDatabaseIT
> [INFO] Running io.pillopl.library.lending.dailysheet.infrastructure.FindingOverdueCheckoutsInDailySheetDatabaseIT
> [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.034 s - in io.pillopl.library.lending.dailysheet.infrastructure.FindingOverdueCheckoutsInDailySheetDatabaseIT
> [INFO] Running io.pillopl.library.lending.eventspropagation.EventualConsistencyBetweenAggregatesAndReadModelsIT
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.697 s - in io.pillopl.library.lending.eventspropagation.EventualConsistencyBetweenAggregatesAndReadModelsIT
> [INFO] Running io.pillopl.library.lending.eventspropagation.StrongConsistencyBetweenAggregatesAndReadModelsIT
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s - in io.pillopl.library.lending.eventspropagation.StrongConsistencyBetweenAggregatesAndReadModelsIT
> [INFO] Running io.pillopl.library.lending.patron.infrastructure.PatronDatabaseRepositoryIT
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 s - in io.pillopl.library.lending.patron.infrastructure.PatronDatabaseRepositoryIT
> [INFO] Running io.pillopl.library.lending.patronprofile.infrastructure.FindingPatronProfileInDatabaseIT
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 s - in io.pillopl.library.lending.patronprofile.infrastructure.FindingPatronProfileInDatabaseIT
> [INFO] Running io.pillopl.library.lending.patronprofile.web.PatronProfileControllerIT
> (...)
> [INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.455 s - in io.pillopl.library.lending.patronprofile.web.PatronProfileControllerIT
> (...)
> [INFO] Tests run: 33, Failures: 0, Errors: 0, Skipped: 0

There's log about `BookDatabaseRepositoryIT` whis is annoted with `@SpringBootTest`
but there's no log about `MeteredDomainEventPublisherSpec` test which is weird.

Changing `MeteredDomainEventPublisherSpec` test to something like:
```
        then:
            countedEvents("domain_events", "name", "TestEvent") == 12121
        when:
            publisher.publish(new TestEvent())
        then:
            countedEvents("domain_events", "name", "TestEvent") == 13131
```

Clearly proves that this test is not runned.

**Comment by pilloPl** [comment]
Hi,

Do you want to find a root cause and provide solution?

**Comment by KamilWitkowski7** [comment]
> Hi,
> 
> Do you want to find a root cause and provide solution?

Hey, not yet.

**Comment by mszarlinski** [comment]
@KamilWitkowski7 try running `mvn integration-test` :)

**Comment by mszarlinski** [comment]
My bad, I will fix it. Test class name should end with `IT` :)
