### ISSUE TITLE
Architecture hexagonal ?

### ISSUE THREAD

**Issue by lowdev** [ddd-by-examples/library#53]
Hi,

Thank you for your example.

I have remarks about your implementation of architecture hexagonal pattern.
In architecture hexagonal we have port and adapter.
In my understanding,
Port is in domain package and adapter in infrastructure package.
(Golden rule : Infra can see domain.
Domain shouldn't see infra.)

However in your package catalogue you have CatalogueDatabase (adapter) and 
CatalogueConfiguration (infra) and Catalogue (domain).

Do you really follow archi hexagonal pattern or am I wrong somewhere ?

**Comment by lowdev** [comment]
Lending package seems to me more in adequation with archi hexagonal.

**Comment by pilloPl** [comment]
Hi, have you read the manual?

> Bounded contexts should (amongst others) introduce autonomy in the sense of architecture. Thus, each module encapsulating the context has its own local architecture aligned to problem complexity. In the case of a context, where we identified true business logic (lending) we introduced a domain model that is a simplified (for the purpose of the project) abstraction of the reality and utilized hexagonal architecture. In the case of a context, that during Event Storming turned out to lack any complex domain logic, we applied CRUD-like local architecture.

Hexagon is not global architecture, it is local one in modular monolith (applied where it made sense)

**Comment by lowdev** [comment]
Sorry, I didn't read that.
I'm new on this pattern in my research I felt in your repo.

The crud approach for "catalogue" seems fair to me.

Thanks a lot for your response and thank again for your repo.
