### ISSUE TITLE
Patron definition

### ISSUE THREAD

**Issue by ghost** [ddd-by-examples/library#58]
A question about your definition of patron ... "anyone who lends books in a library". Did you mean "lend"? Or did you mean "borrow"? Given my understanding of library terms, libraries "lend" things to patrons who "borrow" them. A patron is sometimes referred to as a "borrower".

https://products.abc-clio.com/ODLIS/odlis_b.aspx#borrower

Thanks

**Comment by bslota** [comment]
Hi @stephenjohnwilliams! Thank you, that is a good catch! Would you like to deliver an update in the docs?
