### ISSUE TITLE
[Question] hold_database_entity and overdue_checkout_database_entity table not used?

### ISSUE THREAD

**Issue by liaowang11** [ddd-by-examples/library#60]
`create_patron_db.sql` contains DDL to create `patron_database_entity`, `hold_database_entity` and `overdue_checkout_database_entity`. But it seems the later two are never used. `io.pillopl.library.lending.patron.infrastructure.PatronsDatabaseRepository` just query from patron_database_entity without joining from the other two tables.

```java
interface PatronEntityRepository extends CrudRepository<PatronDatabaseEntity, Long> {

    @Query("SELECT p.* FROM patron_database_entity p where p.patron_id = :patronId")
    PatronDatabaseEntity findByPatronId(@Param("patronId") UUID patronId);

}
```

**Comment by sgnsajgon** [comment]
These tables are used implicitly by Spring Data JDBC, using naming conventions:

```
class PatronDatabaseEntity {
    Set<HoldDatabaseEntity> booksOnHold;
    Set<OverdueCheckoutDatabaseEntity> checkouts;
```

Spring Data JBDC assumes that **Set** is relation, **HoldDatabaseEntity** means table/foreign named **hold_database_entity**.

**Comment by liaowang11** [comment]
Thanks for the tip, found the convention in the [reference](https://docs.spring.io/spring-data/jdbc/docs/1.1.0.RC2/reference/html/#jdbc.mybatis.conventions)
